status-im/nim-stew

std_shims.nimble
std_shims/README.md
std_shims/os_shims.nim
support/README.md
support/bitops2.nim

bitops2 module based on https://github.com/nim-lang/Nim/pull/9029 and what's in `stint` already

add bitops2

---

stew/bitops2.nim
stew/bitseqs.nim
stew/endians2.nim
stew/objects.nim
stew/ranges/bitranges.nim
stew/ranges/ptr_arith.nim
stew/ranges/stackarrays.nim
stew/shims/macros.nim
stew/shims/tables.nim
stew/varints.nim
tests/all_tests.nim
tests/ranges/tbitranges.nim
tests/test_bitseqs.nim
tests/test_varints.nim

Don't merge yet. All branches named "latest-ssz" must be merged together.

Small changes needed by latest versions of nim-faststreams and nim-serialization

---

stew/bitops2.nim
tests/test_bitops2.nim

* use standard bit manipulation naming
* fix signed overflow on large shifts
* add toggle
* add smoke tests
* branch-free changeBit

set, clear, toggle and change bits

---

stew/objects.nim
stew/results.nim
tests/test_objects.nim

Please see the commit comments.

results.Opt and objects.declval

---

stew/ctops.nim
tests/test_ctops.nim

Add tests for different integer types.

Allow any integer type to use CT.isEqual().

---

README.md
stew/arrayops.nim
stew/assign2.nim
stew/byteutils.nim
stew/sequtils2.nim
tests/test_arrayops.nim
tests/test_assign2.nim
tests/test_byteutils.nim
tests/test_sequtils2.nim

* arrayops as a home for small array/openArray utilities
* assign2 - a replacement for genericAssign and assignment operators in
general which in nim are very slow
* use assign2 in a few places to speed things up

random helpers

---

stew/results.nim
tests/test_results.nim

Revert "Allow comparing Result[void, E]"

---

stew/base10.nim
tests/test_base10.nim

Fix issue with `uint` type.

---

stew/bitops2.nim
tests/test_bitops2.nim

should return zeros based on bits, not bytes!

fix `countZeros`

---

stew/shims/macros.nim

This fix by @Araq actually fixes all my problems with generic sandwiches.
CC @Araq @zah @arnetheduck

Fix generic sandwich problem

---

stew/results.nim
tests/test_results.nim

result: expose value/error in errorOr/valueOr

---

stew/ptrops.nim

Because of https://github.com/nim-lang/Nim/issues/19603; fixes https://github.com/status-im/nimbus-eth2/issues/3456

prevent leakage of ptrops checks pragma disabling

---

stew/results.nim
tests/test_results.nim

result: add `Opt.some` / `Opt.none`

---

stew/leb128.nim

leb128: avoid shifts larger than type

---

stew/io2.nim

pls also bump new version , as its important package.

fix int set

---

stew/results.nim

See also: https://github.com/status-im/nim-stew/issues/161#issuecomment-1397121386

results: document experimental error shortcut, and its gotchas

---

stew/results.nim
tests/all_tests.nim
tests/test_results2.nim

See:
* https://github.com/nim-lang/Nim/issues/3770
* https://github.com/nim-lang/Nim/issues/20900

results: work around field access bugs

---

.github/workflows/ci.yml

See https://github.com/actions/runner-images/issues/6002

switch CI to the supported version of ubuntu

---

stew/results.nim

* better error messages and less pollution

result: void-ness tightenings

---

stew/results.nim
tests/test_results.nim

https://github.com/nim-lang/Nim/issues/22049

results: work around nim codegen bug

---

stew/ptrops.nim
tests/test_ptrops.nim

turns a pointer into an array pointer of the same type

ptrops: add makeUncheckedArray

---

stew/results.nim
tests/test_results.nim

fix results compiletime regression

---

stew/shims/strformat.nim
tests/all_tests.nim
tests/test_strformat.nim

https://github.com/nim-lang/Nim/pull/23356

strformat: compile-time format string parser (backport Nim 2.2)

---

stew/arraybuf.nim

https://github.com/nim-lang/Nim/issues/24260
https://github.com/nim-lang/Nim/issues/24261

arraybuf: fix dangling pointer and name workaround

---

stew/base36.nim
tests/test_base36.nim

Added base36 encoding and decoding

feat: add base36

---

stew/assign2.nim

See also https://github.com/nim-lang/Nim/pull/22767

assign: Use `setLenUninit` when growing `seq`

---

stew/results.nim

Deprecated 14 months ago:
- https://github.com/status-im/nim-stew/pull/219

rm deprecated stew/results
