status-im/nim-stew

- README.md
- stew/ptrops.nim
- stew/ranges/ptr_arith.nim
- tests/all_tests.nim
- tests/test_ptrops.nim
This adds ptr ops to `stew` - it has previously been discussed in relation to `nim-serialization`, `ssz` and std library.. 
Names are long on purpose so that one can look for them in code, and follow naming conventions drawn from C++ and rust - in particular, `shift` is typically associated with bit shifting.
> ptrops: add

- stew/result.nim
- tests/test_result.nim
* fix ResultError type
* add/fix documentation
* clean up raises (in preparation for better Defect handling)
* fix toException mixin
* work around compiler bug with more explicit types
* fix capture exception type
* fix result type on `?`
these are the non-breaking changes in #19 / #20
> result: cleanups

- stew/ranges.nim
- stew/ranges/memranges.nim
- stew/ranges/typedranges.nim
Without lifetime tracking, ranges pose a number of issues with regards
to memory safety - use openArray instead which is limited but safe.
In its present form, ranges take a copy of whatever is passed to them
which obscures the copies that they take, leading to misleading and slow
code.
If openArray is not applicable, simply do a seq copy - it's fine and
really doesn't matter in 95% of all cases, then profile and use other
techniques where needed.
> deprecate ranges

- stew/results.nim
- tests/test_results.nim
Useful for translating `error` results
> heterogenous `or`

- stew/endians2.nim
Renamed the `builtin_bswapT` procedures of the vcc compiler to `swapBytesBuiltin`, to then work correctly with compile `-d:swapBytesBuiltin --cc:vcc`
fix [#38](https://github.com/status-im/nim-stew/issues/38)
> fixes for `-d:swapBytesBuiltin --cc:vcc`

- stew.nimble
- stew/bitops2.nim
- stew/endians2.nim
I was wondering why I saw native nim versions in performance traces...
> fix use of compiler intrinsics in endians/bitops

- stew/bitops2.nim
- stew/leb128.nim
- stew/varints.nim
- tests/test_leb128.nim
Leb128 is a variable-length encoding for unsigned integers that is used
in a number of contexts - in particular, wasm, dwarf and protobuf.
This is an optimized low-level implementation that unrolls the loop
reading/writing the buffer - it is suitable to use as base for a more
specific API - no memory allocations, no exceptions.
This PR also fixes bitops2 to not raise on certain `uint->int`
conversions, adapting `bitops2` to nim 1.0 conversion rules by using a cast
instead of raising on `uint->int` conversion
> leb128 + bitops fixes

- stew/results.nim
- tests/test_results.nim
This allow comparing `Result[void, E]` types.
Also simplify the signature
```Nim
func `==`*[T0, E0, T1, E1](lhs: Result[T0, E0], rhs: Result[T1, E1]): bool {.inline.} =
```
The case where `==` is defined for 2 different types is very rare, unused in our case and it's better to an explicit conversion anyway and people can use a converter otherwise.
This might even improve compilation time by being less taxing on the number of generics to keep track of.
> Allow comparing Result[void, E]

- stew/base64.nim
- tests/test_base64.nim
the decoder accepts string or byte sequence but assume
the inner type is a char, now fixed
> fixes bug in base64 decoder when decoding byte sequence

- stew/sorted_set.nim
why:
The name clear() is commonly used as reset function.
> Fix canonical name

- stew/arrayops.nim
- stew/endians2.nim
- tests/test_arrayops.nim
Looking at generated assembly, it turns out the optimizer is not smart
enough to get rid of the loop - use `copyMem` instead.
At least the compiler is smart enough to constant-propagate runtime
endian direction, resolving the review comment.
Also clarify why a minimum length is enfored - it could perhaps be
revisited, but that would leave a slightly odd API.
> endians2: use copyMem instead of loop outside of vm

- stew/byteutils.nim
> byteutils: drop import of assign2 since arrayops imports/exports it

- stew/results.nim
- tests/test_results.nim
* add full support for `Result[T, void]` (aka `Opt[T]` aka `Option[T]`)
* expand tests
* add `flatten`, `filter` of `Option` fame
* add `tryError` that raises a regular exception when result holds a
value
* fix `$` to print `ok`/`err` in lower-case, like the functions that
created the result
* add `orErr` that collapses all errors to a single value of a
potentially different type - useful when translating errors between
layers
* avoid redundant error message when converting error to string
* avoid multiple evaluation in `valueOr`
* add `unsafeError` to match `unsafeGet`
* let `valueOr` evaluate a block
* add `errorOr` to mirror `valueOr`
> `Result` refresh

- stew/results.nim
- tests/test_results.nim
mostly for consistency.. but it's used in nim-eth tests
> results: `[]` for void

- stew/byteutils.nim
- stew/ptrops.nim
The net effect of this change is:
```diff
--- ptrops_orig.nim.c	2022-03-16 17:56:35.054520879 +0100
+++ ptrops.nim.c	2022-03-16 17:56:55.126262722 +0100
@@ -21,6 +21,9 @@
#define nimln_(x, y)
N_LIB_PRIVATE N_NIMCALL(void, test_offset__GUeAIxBAJ79bdeFn6EpeyzA)(void);
N_LIB_PRIVATE N_NIMCALL(void, test_distance__GUeAIxBAJ79bdeFn6EpeyzA_2)(void);
+N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
+static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
+N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
@@ -36,17 +39,41 @@
bytesX60gensym4618021_ = ((NI) 24);
c = ((NI*) (((void*) ((NU)((NU64)(((NU) …
```
> don't disable checks in ptrops

- stew/objects.nim
- tests/test_objects.nim
Add one macro and one procedure:
- macro enumRangeOrd(e: type[enum]): untyped
Creates an array with all the ordinal value of an enum (sorted by default from what I saw)
```nim
type
Test = enum
A1 = 1, B1 = 2, C1 = 3
TestWithHoles = enum
A2 = 1, B2 = 3, C2 = 5
assert(enumRangeOrd(Test) == [ 1, 2, 3 ])
assert(enumRangeOrd(TestWithHoles) == [ 1, 3, 5 ])
```
- proc contains(e: type[enum], v: SomeInteger): bool
With the macro described above, it checks if an integer is in the enum, in order to use someInt in / notin RandomEnum
In addition to that, I use those two macro/proc to implement the hole management in the macro hasHoles and the proc checkEnumAssign
> Add enum utilities and add enum with holes support

- stew.nimble
- stew/shims/macros.nim
- tests/all_tests.nim
- tests/ranges/all.nim
- tests/ranges/tbitranges.nim
- tests/ranges/tstackarrays.nim
- tests/ranges/ttypedranges.nim
- tests/test_assign2.nim
- tests/test_bitops2.nim
- tests/test_bitseqs.nim
- tests/test_byteutils.nim
- tests/test_ctops.nim
- tests/test_endians2.nim
- tests/test_interval_set.nim
- tests/test_io2.nim
- tests/test_keyed_queue.nim
- tests/test_macros.nim
- tests/test_ptrops.nim
- tests/test_results.nim
- tests/test_sequtils2.nim
- tests/test_sets.nim
- tests/test_sorted_set.nim
- tests/test_templateutils.nim
- tests/test_varints.nim
- tests/test_winacl.nim
https://github.com/nim-lang/Nim/pull/17529
https://github.com/nim-lang/Nim/pull/19822
> stylecheck: nnkArglist -> nnkArgList

- stew/arrayops.nim
- stew/assign2.nim
- stew/base10.nim
- stew/bitseqs.nim
- stew/byteutils.nim
- stew/interval_set.nim
- stew/io2.nim
- stew/keyed_queue.nim
- stew/shims/net.nim
- stew/sorted_set.nim
- stew/sorted_set/rbtree_delete.nim
- stew/sorted_set/rbtree_desc.nim
- stew/sorted_set/rbtree_find.nim
- stew/sorted_set/rbtree_flush.nim
- stew/sorted_set/rbtree_insert.nim
- stew/sorted_set/rbtree_reset.nim
- stew/sorted_set/rbtree_rotate.nim
- stew/sorted_set/rbtree_verify.nim
- stew/sorted_set/rbtree_walk.nim
A continuation of https://github.com/status-im/nimbus-eth2/pull/3888
Rationale (from that link):
> Currently (the latest commit in unstable branch), the CI log for the 1.6 branch has **107.000 lines**.
Removing every hint about cannot raise 'Defect' (including the ones in the vendor directory) leaves **16.000 lines**. 85% off.
> make it more Nim 1.4+ compatible

- stew/sorted_set/rbtree_desc.nim
In _nwaku_ we have been using nim 1.6 for some time. This fixes the following deprecation warning:
```
/nwaku/vendor/nim-stew/stew/sorted_set/rbtree_desc.nim(197, 30) Warning: Deprecated since v1.4; there should not be `high(value)`. Use `high(type)`.; high is deprecated [Deprecated]
```
> chore: fix 'there should not be `high(value)`. use `high(type)`' deprecation

- stew/objects.nim
- tests/test_objects.nim
From a quick sweep in our repos, no one uses it
It's based on quite unsafe behavior, doesn't give the same results with arc/orc, and I'm pretty sure a macro could do it, if we need it
> Deprecate baseType

- stew/ptrops.nim
- stew/ranges/ptr_arith.nim
- tests/test_ptrops.nim
* return `nil` for empty openArrays / avoid returning `16`
* move to `ptrops`, deprecate `ptr_arith` fully
> fix `baseAddr`, move to `ptrops`

- stew/byteutils.nim
- tests/test_byteutils.nim
This PR supercedes #144 to allow empty outputs in hex parsing
> byteutils: allow empty output buffers

- nimble.lock
The lock file breaks devel testing - CI updates are needed as well as a strategy for handling "nim important packages" builds (which build with a version of Nim different from that in the lock file)
> Remove lock file

- stew/results.nim
- tests/test_results.nim
These two helpers complete `valueOr` and `errorOr` to cover `void` cases where no value should be returned or `Result[void, E]` / `Result[T, void]` is being used - they can be used for a convient early-return style in side-effectful proc:s:
```nim
v.update().isOkOr:
echo "update failed: ", error
```
> results: Add `isOkOr`, `isErrOr`

- stew/enums.nim
- stew/shims/enumutils.nim
- stew/shims/typetraits.nim
- tests/all_tests.nim
- tests/test_enums.nim
For serialization and parsing, distinguishing enums with numeric values from enums with associated strings for each value is useful. This adds foundational helpers to allow such distinction.
> add `enumStyle` helper macro

- stew/results.nim
- tests/test_results.nim
This set of helpers allows treating Result and Opt as collections of 0 or 1 item, allowing iterating over them and checking "membership" - such integration is useful in generic code which can then be generalised to handle more complex cases - the integration is most useful with Opt.
One design tradeoff here is the "explicitness" of `items` vs `values` for `Result` - technically error and value are "equal" and therefore we shouldn't give preference to the value, but there exists a convenience argument to treat the value as the "default" and therefore define `items` / `contains` for `Result` as well - this PR chooses the more conservative and explicit approach - a more liberal version can easily be added later should motivating examples emerge.
> results: collections integration

- stew/results.nim
Nim emits `ProveField` warnings with `if` on case object discriminator. Replace with `case` instead to avoid those warnings. Note we currently have `ProveField` disabled but it keeps showing up sometimes when compiling with `nim c` instead of `make`.
> fix `ProveField` warnings in `results`

- stew/shims/os.nim
Nim 1.2 and newer unconditionally [define](https://github.com/nim-lang/Nim/blob/version-1-2/lib/pure/os.nim#L3204) and [document  `getCurrentProcessId`](https://nim-lang.org/docs/os.html#getCurrentProcessId):
```nim
proc getCurrentProcessId*(): int {.noWeirdTarget.} =
##
when defined(windows):
proc GetCurrentProcessId(): DWORD {.stdcall, dynlib: "kernel32",
importc: "GetCurrentProcessId".}
result = GetCurrentProcessId().int
else:
result = getpid()
```
which adds some comments, uses `result = foo`, and explicitly checks via `.noWeirdTarget.` for some cases in which the `nim-stew` shim won't work either, but is otherwise functionally equivalent.
> unconditionally pass through std/os and deprecate shim/os

- stew/results.nim
- tests/test_results.nim
We already have `mapConvert` and `mapCast` - this completes the API with corresponding `Err` versions similar to `mapErr`.
The `Convert` / `Cast` operators are of somewhat dubious value - ie they exist as "efficiency" shortcuts for `map` for the case that the mapping should be done as a simple cast / conversion - an alternative would be to deprecate these features and aim for some other, more generic version that involves a type conversion library such as https://github.com/status-im/nim-stew/pull/34, though this inherently, and perhaps rightly, would be limited to "error-free" conversions.
Regardless, these helpers provide balance to the existing API.
> results: add `mapConvertErr`, `mapCastErr`

- stew/io2.nim
on cached data, it doubles read time (!)
> avoid zeroMem

- stew/shims/net.nim
See https://github.com/status-im/nimbus-eth2/pull/5536 for the warnings this triggers.
They're not spurious/false positives, either. `nim-eth` (https://github.com/nim-lang/Nim/issues/22883 affects it since it uses sets and tables with `ValidIpAddress`, `nim-confutils`, and `nim-toml-serialization` all depend on `default(ValidIpAddress)` working, in ways which extend into Nim's standard library.
> don't require init on `ValidIpAddress`

- stew/byteutils.nim
- tests/test_byteutils.nim
> byteutils: `openArray[char]` version of `toBytes`

- stew/shims/net.nim
This module exists to support `ValidIpAddress`, which is deprecated. Otherwise, using `std/net` is equivalent.
> mark stew/shims/net as deprecated

- tests/ranges/tstackarrays.nim
The `Allocating with a negative size throws a RangeError` test actually tests for `RangeDefect`, so rename the test accordingly.
> rename `RangeError` -> `RangeDefect` in test name

- stew/shims/atomics.nim
- stew/shims/enumutils.nim
- stew/shims/stddefects.nim
- stew/shims/typetraits.nim
Followup to
- https://github.com/status-im/nim-stew/pull/205
- https://github.com/status-im/nim-stew/pull/206
It's been virtually a year now, and the updates required in each case are trivial, since
- https://github.com/status-im/nim-stew/pull/204
means people using current commits of `stew` already must be using Nim 1.6 or newer.
> rm deprecated pre-Nim 1.6 shims

- stew/keyed_queue.nim
This change avoids many superfluous data copies and lookups by exploiting `withValue` thus performing only one lookup with the same key (instead of hasKey + actual lookup).
We also avoid several copies of the value which often is copied even though only the next/prev pointers from the item are needed, for example during shifting, deleting and lru-appending.
> keyed_queue: avoid copies, lookups

- stew/io2.nim
- stew/windows/acl.nim
- tests/test_io2.nim
- tests/test_winacl.nim
Fix Windows ACL flakiness issue.
Add getHomePath(), getConfigPath(), getCachePath() and getTempPath() helpers.
> Fix Windows ACL flakiness issue (Windows error 1336).

- stew/base10.nim
- stew/interval_set.nim
- stew/io.nim
- stew/io2.nim
- stew/keyed_queue.nim
- stew/keyed_queue/kq_debug.nim
- stew/shims/os.nim
- stew/sorted_set.nim
- stew/sorted_set/rbtree_delete.nim
- stew/sorted_set/rbtree_desc.nim
- stew/sorted_set/rbtree_find.nim
- stew/sorted_set/rbtree_insert.nim
- stew/sorted_set/rbtree_verify.nim
- stew/sorted_set/rbtree_walk.nim
- tests/test_helper.nim
- https://github.com/status-im/nim-stew/pull/199 deprecated `shims/os` a year ago
- `shims/io` was effectively a workaround for pre-Nim 1.2, or maybe even pre-Nim 1.0. Been several years since it's mattered. The stdlib's [writeFile()](https://nim-lang.org/docs/syncio.html#writeFile%2Cstring%2CopenArray%5Bbyte%5D) can be used as an exact replacement. Verified that under Nim 1.6 and Nim 2.0, that `when` branch doesn't even trigger, so it's been a no-op of an import.
> fix deprecation warnings from results; deprecate shims/io module; rm deprecated shims/os module

- stew/arraybuf.nim
- stew/evalonce.nim
- tests/all_tests.nim
- tests/test_arraybuf.nim
Also includes `evalOnceAs`, a handy utility for avoiding creating a temporary in templates when seeking to avoid double-evaluation of parameters.
> arraybuf: seq-like fixed-capacity container stored on the stack

- stew/objects.nim
- stew/shims/sets.nim
For example, given
```nim
import stew/objects
discard isZeroMemory(default(array[1024, byte]))
```
The previous code under Nim 2.0.8 with `refc` compiles to:
```c
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL,
_ZN7objects12isZeroMemoryE5arrayI10range010235uInt8E)(
tyArray__P46RzO9bG1lpfJxQ2itJfAA x_p0) {
NIM_BOOL result;
{
result = (NIM_BOOL)0;
{
NU8 b;
tyArray__P46RzO9bG1lpfJxQ2itJfAA colontmp_;  /* stack copy of the array */
NI i;
b = (NU8)0;
nimZeroMem((void *)colontmp_, sizeof(tyArray__P46RzO9bG1lpfJxQ2itJfAA));
nimCopyMem((void *)colontmp_, (NIM_CONST void *)((NU8 *)(x_p0)),
sizeof(tyArray__P46RzO9bG1lpfJxQ2itJfAA));
i = ((NI)0);
{
while (1) {
b = colontmp_[(i)-0];
{
if (!!((b == ((NU8)0))))
goto LA6_;
result = NIM_FALSE;
goto BeforeRet_;
}
LA6_:;
{
if (!(((NI)1023) <= ((NI)(i))))
goto LA10_; …
```
> work around pointless copy in isZeroMemory

- stew/arraybuf.nim
- tests/test_arraybuf.nim
also add a block to avoid symbol leaks
> arraybuf: new constructor

- README.md
- stew.nimble
Introduce a new versioning strategy for stew, now that nimble has become more competent at dealing with versions.
> Initial versioned release (v0.2.0)

- stew.nimble
- stew/base32.nim
- stew/base58.nim
- stew/base64.nim
- stew/sorted_set/rbtree_rotate.nim
- tests/test_base10.nim
- tests/test_base32.nim
- tests/test_base58.nim
- tests/test_base64.nim
- tests/test_objects.nim
- `nimHasUsed` is true for all versions of NIm supported by `nim-stew`, currently 1.6 and newer;
- prefer `func` to `proc`
- in `BASE32`/`BASE58`/`BASE64`, `BASE` isn't in those contexts an acronym and shouldn't be capitalized as such
> modernize some modules

- stew/assign2.nim
- tests/test_assign2.nim
The `when nimvm` trick didn't work as expected - it also uncovered a bug that when tgt and src overlap (via views like `openArray`), the compile-time version is different from the runtime version - this is bad, but it's also uncertain what to do about it - can't compare addresses at compile time.
> assign2: fix when nimvm / overlaps
